import { KeycodeCategory } from '../keycodes.categories'

const alphabetKeycodesData = {
  KC_A: {
    aliases: '',
    description: '[kbd]a[/kbd] and [kbd]A[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_B: {
    aliases: '',
    description: '[kbd]b[/kbd] and [kbd]B[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_C: {
    aliases: '',
    description: '[kbd]c[/kbd] and [kbd]C[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_D: {
    aliases: '',
    description: '[kbd]d[/kbd] and [kbd]D[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_E: {
    aliases: '',
    description: '[kbd]e[/kbd] and [kbd]E[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_F: {
    aliases: '',
    description: '[kbd]f[/kbd] and [kbd]F[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_G: {
    aliases: '',
    description: '[kbd]g[/kbd] and [kbd]G[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_H: {
    aliases: '',
    description: '[kbd]h[/kbd] and [kbd]H[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_I: {
    aliases: '',
    description: '[kbd]i[/kbd] and [kbd]I[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_J: {
    aliases: '',
    description: '[kbd]j[/kbd] and [kbd]J[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_K: {
    aliases: '',
    description: '[kbd]k[/kbd] and [kbd]K[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_L: {
    aliases: '',
    description: '[kbd]l[/kbd] and [kbd]L[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_M: {
    aliases: '',
    description: '[kbd]m[/kbd] and [kbd]M[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_N: {
    aliases: '',
    description: '[kbd]n[/kbd] and [kbd]N[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_O: {
    aliases: '',
    description: '[kbd]o[/kbd] and [kbd]O[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_P: {
    aliases: '',
    description: '[kbd]p[/kbd] and [kbd]P[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_Q: {
    aliases: '',
    description: '[kbd]q[/kbd] and [kbd]Q[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_R: {
    aliases: '',
    description: '[kbd]r[/kbd] and [kbd]R[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_S: {
    aliases: '',
    description: '[kbd]s[/kbd] and [kbd]S[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_T: {
    aliases: '',
    description: '[kbd]t[/kbd] and [kbd]T[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_U: {
    aliases: '',
    description: '[kbd]u[/kbd] and [kbd]U[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_V: {
    aliases: '',
    description: '[kbd]v[/kbd] and [kbd]V[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_W: {
    aliases: '',
    description: '[kbd]w[/kbd] and [kbd]W[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_X: {
    aliases: '',
    description: '[kbd]x[/kbd] and [kbd]X[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_Y: {
    aliases: '',
    description: '[kbd]y[/kbd] and [kbd]Y[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_Z: {
    aliases: '',
    description: '[kbd]z[/kbd] and [kbd]Z[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
} as const

export default alphabetKeycodesData
