import { KeycodeCategory } from '../keycodes.categories'

const alphabetKeycodesData = {
  KC_A: {
    aliases: '',
    description: 'a and A',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_B: {
    aliases: '',
    description: 'b and B',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_C: {
    aliases: '',
    description: 'c and C',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_D: {
    aliases: '',
    description: 'd and D',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_E: {
    aliases: '',
    description: 'e and E',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_F: {
    aliases: '',
    description: 'f and F',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_G: {
    aliases: '',
    description: 'g and G',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_H: {
    aliases: '',
    description: 'h and H',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_I: {
    aliases: '',
    description: 'i and I',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_J: {
    aliases: '',
    description: 'j and J',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_K: {
    aliases: '',
    description: 'k and K',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_L: {
    aliases: '',
    description: 'l and L',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_M: {
    aliases: '',
    description: 'm and M',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_N: {
    aliases: '',
    description: 'n and N',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_O: {
    aliases: '',
    description: 'o and O',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_P: {
    aliases: '',
    description: 'p and P',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_Q: {
    aliases: '',
    description: 'q and Q',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_R: {
    aliases: '',
    description: 'r and R',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_S: {
    aliases: '',
    description: 's and S',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_T: {
    aliases: '',
    description: 't and T',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_U: {
    aliases: '',
    description: 'u and U',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_V: {
    aliases: '',
    description: 'v and V',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_W: {
    aliases: '',
    description: 'w and W',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_X: {
    aliases: '',
    description: 'x and X',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_Y: {
    aliases: '',
    description: 'y and Y',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
  KC_Z: {
    aliases: '',
    description: 'z and Z',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.ALPHABET,
  },
} as const

export default alphabetKeycodesData
