import { KeycodeCategory } from '../keycodes-categories'

const functionKeycodesData = {
  KC_PAUSE: {
    Aliases: 'KC_PAUS, KC_BRK, KC_BRMU',
    Description: 'Pause, Brightness Up (macOS)',
    Windows: '✔',
    macOS: '✔<sup>2</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_INSERT: {
    Aliases: 'KC_INS',
    Description: 'Insert',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_HOME: {
    Aliases: '',
    Description: 'Home',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_PGUP: {
    Aliases: '',
    Description: 'Page Up',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_END: {
    Aliases: '',
    Description: 'End',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_PGDOWN: {
    Aliases: 'KC_PGDN',
    Description: 'Page Down',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_NUMLOCK: {
    Aliases: 'KC_NLCK',
    Description: 'Keypad Num Lock and Clear',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_AUDIO_MUTE: {
    Aliases: 'KC_MUTE',
    Description: 'Mute',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_AUDIO_VOL_UP: {
    Aliases: 'KC_VOLU',
    Description: 'Volume Up',
    Windows: '✔',
    macOS: '✔<sup>4</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_AUDIO_VOL_DOWN: {
    Aliases: 'KC_VOLD',
    Description: 'Volume Down',
    Windows: '✔',
    macOS: '✔<sup>4</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MEDIA_NEXT_TRACK: {
    Aliases: 'KC_MNXT',
    Description: 'Next Track',
    Windows: '✔',
    macOS: '✔<sup>5</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MEDIA_PREV_TRACK: {
    Aliases: 'KC_MPRV',
    Description: 'Previous Track',
    Windows: '✔',
    macOS: '✔<sup>5</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MEDIA_STOP: {
    Aliases: 'KC_MSTP',
    Description: 'Stop Track',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MEDIA_PLAY_PAUSE: {
    Aliases: 'KC_MPLY',
    Description: 'Play/Pause Track',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MEDIA_SELECT: {
    Aliases: 'KC_MSEL',
    Description: 'Launch Media Player',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MEDIA_EJECT: {
    Aliases: 'KC_EJCT',
    Description: 'Eject',
    Windows: '',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MAIL: {
    Aliases: '',
    Description: 'Launch Mail',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_CALCULATOR: {
    Aliases: 'KC_CALC',
    Description: 'Launch Calculator',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MY_COMPUTER: {
    Aliases: 'KC_MYCM',
    Description: 'Launch My Computer',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_WWW_SEARCH: {
    Aliases: 'KC_WSCH',
    Description: 'Browser Search',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_WWW_HOME: {
    Aliases: 'KC_WHOM',
    Description: 'Browser Home',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_WWW_BACK: {
    Aliases: 'KC_WBAK',
    Description: 'Browser Back',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_WWW_FORWARD: {
    Aliases: 'KC_WFWD',
    Description: 'Browser Forward',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_WWW_STOP: {
    Aliases: 'KC_WSTP',
    Description: 'Browser Stop',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_WWW_REFRESH: {
    Aliases: 'KC_WREF',
    Description: 'Browser Refresh',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_WWW_FAVORITES: {
    Aliases: 'KC_WFAV',
    Description: 'Browser Favorites',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MEDIA_FAST_FORWARD: {
    Aliases: 'KC_MFFD',
    Description: 'Next Track',
    Windows: '✔',
    macOS: '✔<sup>5</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MEDIA_REWIND: {
    Aliases: 'KC_MRWD',
    Description: 'Previous Track',
    Windows: '✔<sup>6</sup>',
    macOS: '✔<sup>5</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_BRIGHTNESS_UP: {
    Aliases: 'KC_BRIU',
    Description: 'Brightness Up',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_BRIGHTNESS_DOWN: {
    Aliases: 'KC_BRID',
    Description: 'Brightness Down',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },

  KC_F1: {
    Aliases: '',
    Description: 'F1',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F2: {
    Aliases: '',
    Description: 'F2',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F3: {
    Aliases: '',
    Description: 'F3',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F4: {
    Aliases: '',
    Description: 'F4',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F5: {
    Aliases: '',
    Description: 'F5',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F6: {
    Aliases: '',
    Description: 'F6',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F7: {
    Aliases: '',
    Description: 'F7',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F8: {
    Aliases: '',
    Description: 'F8',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F9: {
    Aliases: '',
    Description: 'F9',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F10: {
    Aliases: '',
    Description: 'F10',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F11: {
    Aliases: '',
    Description: 'F11',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F12: {
    Aliases: '',
    Description: 'F12',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F13: {
    Aliases: '',
    Description: 'F13',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F14: {
    Aliases: '',
    Description: 'F14',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F15: {
    Aliases: '',
    Description: 'F15',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F16: {
    Aliases: '',
    Description: 'F16',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F17: {
    Aliases: '',
    Description: 'F17',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F18: {
    Aliases: '',
    Description: 'F18',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F19: {
    Aliases: '',
    Description: 'F19',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F20: {
    Aliases: '',
    Description: 'F20',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F21: {
    Aliases: '',
    Description: 'F21',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F22: {
    Aliases: '',
    Description: 'F22',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F23: {
    Aliases: '',
    Description: 'F23',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_F24: {
    Aliases: '',
    Description: 'F24',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_PSCREEN: {
    Aliases: 'KC_PSCR',
    Description: 'Print Screen',
    Windows: '✔',
    macOS: '✔<sup>2</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_SCROLLLOCK: {
    Aliases: 'KC_SLCK, KC_BRMD',
    Description: 'Scroll Lock, Brightness Down (macOS)',
    Windows: '✔',
    macOS: '✔<sup>2</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_APPLICATION: {
    Aliases: 'KC_APP',
    Description: 'Application (Windows Context Menu Key)',
    Windows: '✔',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_POWER: {
    Aliases: '',
    Description: 'System Power',
    Windows: '',
    macOS: '✔<sup>3</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_EXECUTE: {
    Aliases: 'KC_EXEC',
    Description: 'Execute',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_HELP: {
    Aliases: '',
    Description: 'Help',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_MENU: {
    Aliases: '',
    Description: 'Menu',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_SELECT: {
    Aliases: 'KC_SLCT',
    Description: 'Select',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_STOP: {
    Aliases: '',
    Description: 'Stop',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_AGAIN: {
    Aliases: 'KC_AGIN',
    Description: 'Again',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_UNDO: {
    Aliases: '',
    Description: 'Undo',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_CUT: {
    Aliases: '',
    Description: 'Cut',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_COPY: {
    Aliases: '',
    Description: 'Copy',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_PASTE: {
    Aliases: 'KC_PSTE',
    Description: 'Paste',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_FIND: {
    Aliases: '',
    Description: 'Find',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC__MUTE: {
    Aliases: '',
    Description: 'Mute',
    Windows: '',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC__VOLUP: {
    Aliases: '',
    Description: 'Volume Up',
    Windows: '',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC__VOLDOWN: {
    Aliases: '',
    Description: 'Volume Down',
    Windows: '',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_LOCKING_CAPS: {
    Aliases: 'KC_LCAP',
    Description: 'Locking Caps Lock',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_LOCKING_NUM: {
    Aliases: 'KC_LNUM',
    Description: 'Locking Num Lock',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_LOCKING_SCROLL: {
    Aliases: 'KC_LSCR',
    Description: 'Locking Scroll Lock',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_ALT_ERASE: {
    Aliases: 'KC_ERAS',
    Description: 'Alternate Erase',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_SYSREQ: {
    Aliases: '',
    Description: 'SysReq/Attention',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_CANCEL: {
    Aliases: '',
    Description: 'Cancel',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_CLEAR: {
    Aliases: 'KC_CLR',
    Description: 'Clear',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_PRIOR: {
    Aliases: '',
    Description: 'Prior',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_RETURN: {
    Aliases: '',
    Description: 'Return',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_SEPARATOR: {
    Aliases: '',
    Description: 'Separator',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_OUT: {
    Aliases: '',
    Description: 'Out',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_OPER: {
    Aliases: '',
    Description: 'Oper',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_CLEAR_AGAIN: {
    Aliases: '',
    Description: 'Clear/Again',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_CRSEL: {
    Aliases: '',
    Description: 'CrSel/Props',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_EXSEL: {
    Aliases: '',
    Description: 'ExSel',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.FUNCTION,
  },
  KC_SYSTEM_POWER: {
    Aliases: 'KC_PWR',
    Description: 'System Power Down',
    Windows: '✔',
    macOS: '✔<sup>3</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_SYSTEM_SLEEP: {
    Aliases: 'KC_SLEP',
    Description: 'System Sleep',
    Windows: '✔',
    macOS: '✔<sup>3</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
  KC_SYSTEM_WAKE: {
    Aliases: 'KC_WAKE',
    Description: 'System Wake',
    Windows: '',
    macOS: '✔<sup>3</sup>',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.FUNCTION,
  },
} as const

export default functionKeycodesData
