import { KeycodeCategory } from '../keycodes-categories'

const navigationKeycodesData = {
  KC_ENT: {
    Aliases: 'KC_ENTER',
    Description: 'Return (Enter)',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_ESC: {
    Aliases: 'KC_ESCAPE',
    Description: 'Escape',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_BSPC: {
    Aliases: 'KC_BSPACE',
    Description: 'Delete (Backspace)',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_TAB: {
    Aliases: '',
    Description: 'Tab',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_SPC: {
    Aliases: 'KC_SPACE',
    Description: 'Spacebar',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_GRV: {
    Aliases: 'KC_GRAVE, KC_ZKHK',
    Description: '<code>&#96;</code> and ~, JIS Zenkaku/Hankaku',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_CAPS: {
    Aliases: 'KC_CAPSLOCK, KC_CLCK',
    Description: 'Caps Lock',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DEL: {
    Aliases: 'KC_DELETE',
    Description: 'Forward Delete',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_RGHT: {
    Aliases: 'KC_RIGHT',
    Description: 'Right Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_LEFT: {
    Aliases: '',
    Description: 'Left Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DOWN: {
    Aliases: '',
    Description: 'Down Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_UP: {
    Aliases: '',
    Description: 'Up Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_PENT: {
    Aliases: 'KC_KP_ENTER',
    Description: 'Keypad Enter',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
} as const

export default navigationKeycodesData
