import { KeycodeCategory } from '../keycodes-categories'

const navigationKeycodesData = {
  KC_ENTER: {
    Aliases: 'KC_ENT',
    Description: 'Return (Enter)',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_ESCAPE: {
    Aliases: 'KC_ESC',
    Description: 'Escape',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_BSPACE: {
    Aliases: 'KC_BSPC',
    Description: 'Delete (Backspace)',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_TAB: {
    Aliases: '',
    Description: 'Tab',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_SPACE: {
    Aliases: 'KC_SPC',
    Description: 'Spacebar',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_GRAVE: {
    Aliases: 'KC_GRV, KC_ZKHK',
    Description: '<code>&#96;</code> and ~, JIS Zenkaku/Hankaku',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_CAPSLOCK: {
    Aliases: 'KC_CLCK, KC_CAPS',
    Description: 'Caps Lock',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DELETE: {
    Aliases: 'KC_DEL',
    Description: 'Forward Delete',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_RIGHT: {
    Aliases: 'KC_RGHT',
    Description: 'Right Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_LEFT: {
    Aliases: '',
    Description: 'Left Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DOWN: {
    Aliases: '',
    Description: 'Down Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_UP: {
    Aliases: '',
    Description: 'Up Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
  KC_KP_ENTER: {
    Aliases: 'KC_PENT',
    Description: 'Keypad Enter',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NAVIGATION,
  },
} as const

export default navigationKeycodesData
