import { KeycodeCategory } from '../keycodes.categories'

const navigationKeycodesData = {
  KC_ENT: {
    aliases: 'KC_ENTER',
    description: 'Return (Enter)',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_ESC: {
    aliases: 'KC_ESCAPE',
    description: 'Escape',
    defaultDisplay: 'Esc',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_BSPC: {
    aliases: 'KC_BSPACE',
    description: 'Delete (Backspace)',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_TAB: {
    aliases: '',
    description: 'Tab',
    defaultDisplay: 'Tab',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_SPC: {
    aliases: 'KC_SPACE',
    defaultDisplay: '⎵',
    description: 'Spacebar',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_GRV: {
    aliases: 'KC_GRAVE, KC_ZKHK',
    defaultDisplay: '`',
    description: '<code>&#96;</code> and ~, JIS Zenkaku/Hankaku',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_CAPS: {
    aliases: 'KC_CAPSLOCK, KC_CLCK',
    description: 'Caps Lock',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DEL: {
    aliases: 'KC_DELETE',
    description: 'Forward Delete',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_RGHT: {
    aliases: 'KC_RIGHT',
    description: 'Right Arrow',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_LEFT: {
    aliases: '',
    description: 'Left Arrow',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DOWN: {
    aliases: '',
    description: 'Down Arrow',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_UP: {
    aliases: '',
    description: 'Up Arrow',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_PENT: {
    aliases: 'KC_KP_ENTER',
    description: 'Keypad Enter',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
} as const

export default navigationKeycodesData
