import { KeycodeCategory } from '../keycodes.categories'

const navigationKeycodesData = {
  KC_ENT: {
    aliases: 'KC_ENTER',
    description: '[kbd]Return[/] ([code]Enter[/])',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_ESC: {
    aliases: 'KC_ESCAPE',
    description: '[kbd]Escape[/]',
    defaultDisplay: 'Esc',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_BSPC: {
    aliases: 'KC_BSPACE',
    description: '[kbd]Backspace[/]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_TAB: {
    aliases: '',
    description: '[kbd]Tab[/]',
    defaultDisplay: 'Tab',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_SPC: {
    aliases: 'KC_SPACE',
    defaultDisplay: '⎵',
    description: '[kbd]Spacebar[/]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_GRV: {
    aliases: 'KC_GRAVE, KC_ZKHK',
    defaultDisplay: '`',
    description: '[kbd]`[/] and [kbd]~[/]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_CAPS: {
    aliases: 'KC_CAPSLOCK, KC_CLCK',
    description: '[kbd]Caps Lock[/]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DEL: {
    aliases: 'KC_DELETE',
    description: '[kbd]Delete[/] ([code]Forward delete[/])',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_RGHT: {
    aliases: 'KC_RIGHT',
    description: 'Right Arrow',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_LEFT: {
    aliases: '',
    description: 'Left Arrow',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DOWN: {
    aliases: '',
    description: 'Down Arrow',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_UP: {
    aliases: '',
    description: 'Up Arrow',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_PENT: {
    aliases: 'KC_KP_ENTER',
    description: 'Keypad [kbd]Enter[/]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
} as const

export default navigationKeycodesData
