import React from 'react'
import {
  ArrowBackIcon,
  ArrowDownIcon,
  ArrowForwardIcon,
  ArrowUpIcon,
} from '@chakra-ui/icons'
import { KeycodeCategory } from '../keycodes.categories'
import { Icon } from '@chakra-ui/react'
import { MdKeyboardReturn, MdKeyboardTab } from 'react-icons/md'
import { BsBackspace, BsBackspaceReverse, BsCapslock } from 'react-icons/bs'

const navigationKeycodesData = {
  KC_ENT: {
    aliases: 'KC_ENTER',
    description: '[kbd]Return[/] ([code]Enter[/])',
    display: <Icon as={MdKeyboardReturn} />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_ESC: {
    aliases: 'KC_ESCAPE',
    description: '[kbd]Escape[/]',
    display: 'esc',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_BSPC: {
    aliases: 'KC_BSPACE',
    description: '[kbd]Backspace[/]',
    display: <Icon as={BsBackspace} />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_TAB: {
    aliases: '',
    description: '[kbd]Tab[/]',
    display: <Icon as={MdKeyboardTab} />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_SPC: {
    aliases: 'KC_SPACE',
    display: '⎵',
    description: '[kbd]Spacebar[/]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_GRV: {
    aliases: 'KC_GRAVE, KC_ZKHK',
    display: '`',
    description: '[kbd]`[/] and [kbd]~[/]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_CAPS: {
    aliases: 'KC_CAPSLOCK, KC_CLCK',
    description: '[kbd]Caps Lock[/]',
    display: <Icon as={BsCapslock} />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DEL: {
    aliases: 'KC_DELETE',
    description: '[kbd]Delete[/] ([code]Forward delete[/])',
    display: <Icon as={BsBackspaceReverse} />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_RGHT: {
    aliases: 'KC_RIGHT',
    description: 'Right Arrow',
    display: <ArrowForwardIcon />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_LEFT: {
    aliases: '',
    description: 'Left Arrow',
    display: <ArrowBackIcon />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_DOWN: {
    aliases: '',
    description: 'Down Arrow',
    display: <ArrowDownIcon />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_UP: {
    aliases: '',
    description: 'Up Arrow',
    display: <ArrowUpIcon />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
  KC_PENT: {
    aliases: 'KC_KP_ENTER',
    description: 'Keypad [kbd]Enter[/]',
    display: <Icon as={MdKeyboardReturn} />,
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NAVIGATION,
  },
} as const

export default navigationKeycodesData
