import { KeycodeCategory } from '../keycodes-categories'

const numericKeycodesData = {
  KC_1: {
    Aliases: '',
    Description: '1 and !',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_2: {
    Aliases: '',
    Description: '2 and @',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_3: {
    Aliases: '',
    Description: '3 and #',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_4: {
    Aliases: '',
    Description: '4 and $',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_5: {
    Aliases: '',
    Description: '5 and %',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_6: {
    Aliases: '',
    Description: '6 and ^',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_7: {
    Aliases: '',
    Description: '7 and &',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_8: {
    Aliases: '',
    Description: '8 and *',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_9: {
    Aliases: '',
    Description: '9 and (',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_0: {
    Aliases: '',
    Description: '0 and )',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_1: {
    Aliases: 'KC_P1',
    Description: 'Keypad 1 and End',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_2: {
    Aliases: 'KC_P2',
    Description: 'Keypad 2 and Down Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_3: {
    Aliases: 'KC_P3',
    Description: 'Keypad 3 and Page Down',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_4: {
    Aliases: 'KC_P4',
    Description: 'Keypad 4 and Left Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_5: {
    Aliases: 'KC_P5',
    Description: 'Keypad 5',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_6: {
    Aliases: 'KC_P6',
    Description: 'Keypad 6 and Right Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_7: {
    Aliases: 'KC_P7',
    Description: 'Keypad 7 and Home',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_8: {
    Aliases: 'KC_P8',
    Description: 'Keypad 8 and Up Arrow',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_9: {
    Aliases: 'KC_P9',
    Description: 'Keypad 9 and Page Up',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_KP_0: {
    Aliases: 'KC_P0',
    Description: 'Keypad 0 and Insert',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.NUMERIC,
  },
} as const

export default numericKeycodesData
