import { KeycodeCategory } from '../keycodes.categories'

const numericKeycodesData = {
  KC_1: {
    aliases: '',
    description: '[kbd]1[/kbd] and [kbd]![/kbd]',
    display: ['1', '!'],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_2: {
    aliases: '',
    description: '[kbd]2[/kbd] and [kbd]@[/kbd]',
    display: ['2', '@'],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_3: {
    aliases: '',
    description: '[kbd]3[/kbd] and [kbd]#[/kbd]',
    display: ['3', '#'],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_4: {
    aliases: '',
    description: '[kbd]4[/kbd] and [kbd]$[/kbd]',
    display: ['4', '$'],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_5: {
    aliases: '',
    description: '[kbd]5[/kbd] and [kbd]%[/kbd]',
    display: ['5', '%'],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_6: {
    aliases: '',
    description: '[kbd]6[/kbd] and [kbd]^[/kbd]',
    display: ['6', '^'],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_7: {
    aliases: '',
    description: '[kbd]7[/kbd] and [kbd]&[/kbd]',
    display: ['7', '&'],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_8: {
    aliases: '',
    description: '[kbd]8[/kbd] and [kbd]*[/kbd]',
    display: ['8', '*'],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_9: {
    aliases: '',
    description: '[kbd]9[/kbd] and [kbd]([/kbd]',
    display: ['9', '('],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_0: {
    aliases: '',
    description: '[kbd]0[/kbd] and [kbd])[/kbd]',
    display: ['0', ')'],
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P1: {
    aliases: 'KC_KP_1',
    description: 'Keypad [kbd]1[/kbd] and [code]End[/code]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P2: {
    aliases: 'KC_KP_2',
    description: 'Keypad [kbd]2[/kbd] and [code]Down Arrow[/code]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P3: {
    aliases: 'KC_KP_3',
    description: 'Keypad [kbd]3[/kbd] and [code]Page Down[/code]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P4: {
    aliases: 'KC_KP_4',
    description: 'Keypad [kbd]4[/kbd] and [code]Left Arrow[/code]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P5: {
    aliases: 'KC_KP_5',
    description: 'Keypad [kbd]5[/kbd]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P6: {
    aliases: 'KC_KP_6',
    description: 'Keypad [kbd]6[/kbd] and [code]Right Arrow[/code]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P7: {
    aliases: 'KC_KP_7',
    description: 'Keypad [kbd]7[/kbd] and [code]Home[/code]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P8: {
    aliases: 'KC_KP_8',
    description: 'Keypad [kbd]8[/kbd] and [code]Up Arrow[/code]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P9: {
    aliases: 'KC_KP_9',
    description: 'Keypad [kbd]9[/kbd] and [code]Page Up[/code]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
  KC_P0: {
    aliases: 'KC_KP_0',
    description: 'Keypad [kbd]0[/kbd] and [code]Insert[/code]',
    Windows: true,
    macOS: true,
    Linux: true,
    category: KeycodeCategory.NUMERIC,
  },
} as const

export default numericKeycodesData
