import { KeycodeCategory } from '../keycodes-categories'

const symbolsKeycodesData = {
  KC_MINS: {
    Aliases: 'KC_MINUS',
    Description: '- and _',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_EQL: {
    Aliases: 'KC_EQUAL',
    Description: '= and +',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_LBRC: {
    Aliases: 'KC_LBRACKET',
    Description: '[ and {',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_RBRC: {
    Aliases: 'KC_RBRACKET',
    Description: '] and }',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_BSLS: {
    Aliases: 'KC_BSLASH',
    Description: '\\ and \\|',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_NUHS: {
    Aliases: 'KC_NONUS_HASH',
    Description: 'Non-US # and ~',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_SCLN: {
    Aliases: 'KC_SCOLON',
    Description: '; and :',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_QUOT: {
    Aliases: 'KC_QUOTE',
    Description: '\' and "',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_COMM: {
    Aliases: 'KC_COMMA',
    Description: ', and <',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_DOT: {
    Aliases: '',
    Description: '. and >',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_SLSH: {
    Aliases: 'KC_SLASH',
    Description: '/ and ?',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PSLS: {
    Aliases: 'KC_KP_SLASH',
    Description: 'Keypad /',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PAST: {
    Aliases: 'KC_KP_ASTERISK',
    Description: 'Keypad *',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PMNS: {
    Aliases: 'KC_KP_MINUS',
    Description: 'Keypad -',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PPLS: {
    Aliases: 'KC_KP_PLUS',
    Description: 'Keypad +',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PDOT: {
    Aliases: 'KC_KP_DOT',
    Description: 'Keypad . and Delete',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_NUBS: {
    Aliases: 'KC_NONUS_BSLASH',
    Description: 'Non-US \\ and \\|',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PEQL: {
    Aliases: 'KC_KP_EQUAL',
    Description: 'Keypad =',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PCMM: {
    Aliases: 'KC_KP_COMMA',
    Description: 'Keypad ,',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_EQUAL_AS400: {
    Aliases: '',
    Description: 'Keypad = on AS/400 keyboards',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.SYMBOLS,
  },
} as const

export default symbolsKeycodesData
