import { KeycodeCategory } from '../keycodes-categories'

const symbolsKeycodesData = {
  KC_MINUS: {
    Aliases: 'KC_MINS',
    Description: '- and _',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_EQUAL: {
    Aliases: 'KC_EQL',
    Description: '= and +',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_LBRACKET: {
    Aliases: 'KC_LBRC',
    Description: '[ and {',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_RBRACKET: {
    Aliases: 'KC_RBRC',
    Description: '] and }',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_BSLASH: {
    Aliases: 'KC_BSLS',
    Description: '\\ and \\|',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_NONUS_HASH: {
    Aliases: 'KC_NUHS',
    Description: 'Non-US # and ~',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_SCOLON: {
    Aliases: 'KC_SCLN',
    Description: '; and :',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_QUOTE: {
    Aliases: 'KC_QUOT',
    Description: '\' and "',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_COMMA: {
    Aliases: 'KC_COMM',
    Description: ', and <',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_DOT: {
    Aliases: '',
    Description: '. and >',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_SLASH: {
    Aliases: 'KC_SLSH',
    Description: '/ and ?',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_SLASH: {
    Aliases: 'KC_PSLS',
    Description: 'Keypad /',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_ASTERISK: {
    Aliases: 'KC_PAST',
    Description: 'Keypad *',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_MINUS: {
    Aliases: 'KC_PMNS',
    Description: 'Keypad -',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_PLUS: {
    Aliases: 'KC_PPLS',
    Description: 'Keypad +',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_DOT: {
    Aliases: 'KC_PDOT',
    Description: 'Keypad . and Delete',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_NONUS_BSLASH: {
    Aliases: 'KC_NUBS',
    Description: 'Non-US \\ and \\|',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_EQUAL: {
    Aliases: 'KC_PEQL',
    Description: 'Keypad =',
    Windows: '✔',
    macOS: '✔',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_COMMA: {
    Aliases: 'KC_PCMM',
    Description: 'Keypad ,',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_EQUAL_AS400: {
    Aliases: '',
    Description: 'Keypad = on AS/400 keyboards',
    Windows: '',
    macOS: '',
    'Linux<sup>1</sup>': '',
    category: KeycodeCategory.SYMBOLS,
  },
} as const

export default symbolsKeycodesData
