import { KeycodeCategory } from '../../keycodes-categories'

const internationalKeycodesData = {
  KC_RO: {
    aliases: 'KC_INT1',
    description: 'JIS \\ and _',
    Windows: '✔',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_KANA: {
    aliases: 'KC_INT2',
    description: 'JIS Katakana/Hiragana',
    Windows: '✔',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_JYEN: {
    aliases: 'KC_INT3',
    description: 'JIS ¥ and \\|',
    Windows: '✔',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_HENK: {
    aliases: 'KC_INT4',
    description: 'JIS Henkan',
    Windows: '✔',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_MHEN: {
    aliases: 'KC_INT5',
    description: 'JIS Muhenkan',
    Windows: '✔',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_INT6: {
    aliases: '',
    description: 'JIS Numpad ,',
    Windows: '',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_INT7: {
    aliases: '',
    description: 'International 7',
    Windows: '',
    macOS: '',
    Linux: '',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_INT8: {
    aliases: '',
    description: 'International 8',
    Windows: '',
    macOS: '',
    Linux: '',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_INT9: {
    aliases: '',
    description: 'International 9',
    Windows: '',
    macOS: '',
    Linux: '',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_HAEN: {
    aliases: 'KC_LANG1',
    description: 'Hangul/English',
    Windows: '',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_HANJ: {
    aliases: 'KC_LANG2',
    description: 'Hanja',
    Windows: '',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_LANG3: {
    aliases: '',
    description: 'JIS Katakana',
    Windows: '',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_LANG4: {
    aliases: '',
    description: 'JIS Hiragana',
    Windows: '',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_LANG5: {
    aliases: '',
    description: 'JIS Zenkaku/Hankaku',
    Windows: '',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_LANG6: {
    aliases: '',
    description: 'Language 6',
    Windows: '',
    macOS: '',
    Linux: '',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_LANG7: {
    aliases: '',
    description: 'Language 7',
    Windows: '',
    macOS: '',
    Linux: '',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_LANG8: {
    aliases: '',
    description: 'Language 8',
    Windows: '',
    macOS: '',
    Linux: '',
    category: KeycodeCategory.INTERNATIONAL,
  },
  KC_LANG9: {
    aliases: '',
    description: 'Language 9',
    Windows: '',
    macOS: '',
    Linux: '',
    category: KeycodeCategory.INTERNATIONAL,
  },
} as const

export default internationalKeycodesData
