import { KeycodeCategory } from '../../keycodes-categories'

const numericKeycodesData = {
  KC_1: {
    aliases: '',
    description: '1 and !',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_2: {
    aliases: '',
    description: '2 and @',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_3: {
    aliases: '',
    description: '3 and #',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_4: {
    aliases: '',
    description: '4 and $',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_5: {
    aliases: '',
    description: '5 and %',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_6: {
    aliases: '',
    description: '6 and ^',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_7: {
    aliases: '',
    description: '7 and &',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_8: {
    aliases: '',
    description: '8 and *',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_9: {
    aliases: '',
    description: '9 and (',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_0: {
    aliases: '',
    description: '0 and )',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P1: {
    aliases: 'KC_KP_1',
    description: 'Keypad 1 and End',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P2: {
    aliases: 'KC_KP_2',
    description: 'Keypad 2 and Down Arrow',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P3: {
    aliases: 'KC_KP_3',
    description: 'Keypad 3 and Page Down',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P4: {
    aliases: 'KC_KP_4',
    description: 'Keypad 4 and Left Arrow',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P5: {
    aliases: 'KC_KP_5',
    description: 'Keypad 5',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P6: {
    aliases: 'KC_KP_6',
    description: 'Keypad 6 and Right Arrow',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P7: {
    aliases: 'KC_KP_7',
    description: 'Keypad 7 and Home',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P8: {
    aliases: 'KC_KP_8',
    description: 'Keypad 8 and Up Arrow',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P9: {
    aliases: 'KC_KP_9',
    description: 'Keypad 9 and Page Up',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
  KC_P0: {
    aliases: 'KC_KP_0',
    description: 'Keypad 0 and Insert',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.NUMERIC,
  },
} as const

export default numericKeycodesData
