import { KeycodeCategory } from '../../keycodes-categories'

const symbolsKeycodesData = {
  KC_MINS: {
    aliases: 'KC_MINUS',
    description: '- and _',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_EQL: {
    aliases: 'KC_EQUAL',
    description: '= and +',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_LBRC: {
    aliases: 'KC_LBRACKET',
    description: '[ and {',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_RBRC: {
    aliases: 'KC_RBRACKET',
    description: '] and }',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_BSLS: {
    aliases: 'KC_BSLASH',
    description: '\\ and \\|',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_NUHS: {
    aliases: 'KC_NONUS_HASH',
    description: 'Non-US # and ~',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_SCLN: {
    aliases: 'KC_SCOLON',
    description: '; and :',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_QUOT: {
    aliases: 'KC_QUOTE',
    description: '\' and "',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_COMM: {
    aliases: 'KC_COMMA',
    description: ', and <',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_DOT: {
    aliases: '',
    description: '. and >',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_SLSH: {
    aliases: 'KC_SLASH',
    description: '/ and ?',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PSLS: {
    aliases: 'KC_KP_SLASH',
    description: 'Keypad /',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PAST: {
    aliases: 'KC_KP_ASTERISK',
    description: 'Keypad *',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PMNS: {
    aliases: 'KC_KP_MINUS',
    description: 'Keypad -',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PPLS: {
    aliases: 'KC_KP_PLUS',
    description: 'Keypad +',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PDOT: {
    aliases: 'KC_KP_DOT',
    description: 'Keypad . and Delete',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_NUBS: {
    aliases: 'KC_NONUS_BSLASH',
    description: 'Non-US \\ and \\|',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PEQL: {
    aliases: 'KC_KP_EQUAL',
    description: 'Keypad =',
    Windows: '✔',
    macOS: '✔',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_PCMM: {
    aliases: 'KC_KP_COMMA',
    description: 'Keypad ,',
    Windows: '',
    macOS: '',
    Linux: '✔',
    category: KeycodeCategory.SYMBOLS,
  },
  KC_KP_EQUAL_AS400: {
    aliases: '',
    description: 'Keypad = on AS/400 keyboards',
    Windows: '',
    macOS: '',
    Linux: '',
    category: KeycodeCategory.SYMBOLS,
  },
} as const

export default symbolsKeycodesData
